# Generated by Django 4.2 on 2023-05-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_services_service_slug_alter_services_services_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_image',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='service/'),
        ),
    ]
